export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_TEAM = "SET_CURRENT_TEAM";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";